spring:
  datasource:
# serverTimezone=UTC MySQL jdbc 6.0 版本以上必须配置此参数,时区程序不出错
    url: jdbc:mysql://localhost:3306/vue?serverTimezone=UTC
    username: root
#    家里
    password: root
#    公司
#    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 9080
# 打印sql
logging:
  level:
    com.lying.test.mapper: debug
